/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.dieptt.sleepingwell;

public final class R {
    public static final class array {
        public static final int fileEndingAudio=0x7f040001;
        public static final int fileEndingGeoPosition=0x7f040006;
        public static final int fileEndingImage=0x7f040000;
        public static final int fileEndingPackage=0x7f040002;
        public static final int fileEndingText=0x7f040004;
        public static final int fileEndingVideo=0x7f040005;
        public static final int fileEndingWebText=0x7f040003;
        public static final int file_options=0x7f040007;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int archive=0x7f020000;
        public static final int audio=0x7f020001;
        public static final int directory=0x7f020002;
        public static final int geoposition=0x7f020003;
        public static final int ic_launcher=0x7f020004;
        public static final int icon=0x7f020005;
        public static final int image=0x7f020006;
        public static final int text=0x7f020007;
        public static final int unknown=0x7f020008;
        public static final int updirectory=0x7f020009;
        public static final int video=0x7f02000a;
        public static final int webdoc=0x7f02000b;
    }
    public static final class id {
        public static final int GridView=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
}
